/**
 * Types for the Texto SMS API. Generated by hand from api/openapi.yaml —
 * keep both in step when the API changes.
 */

export type ServiceState = "operational" | "degraded";

export interface StatusResponse {
  status: ServiceState;
  timestamp: string;
  version: string;
  services: {
    outbound: ServiceState;
    inbound: ServiceState;
    delivery_receipts: ServiceState;
  };
}

export interface BalanceResponse {
  credits: number;
}

export interface SendParams {
  /** Recipient mobile number. AU numbers accept 04xxxxxxxx, 614xxxxxxxx or +614xxxxxxxx. */
  to: string;
  message: string;
  /** A dedicated number or approved Sender ID owned by the account. */
  sender?: string;
  /** Override the account's link shortening and click tracking for this message. */
  linkTracking?: boolean;
  /** Attach the message to a campaign with this name, creating it if needed. */
  campaign?: string;
}

export interface SendResponse {
  message_id: string;
  credits_used: number;
  /** Omitted for postpaid accounts. */
  credits_remaining?: number;
}

export type BatchRecipient = string | { phone: string; merge_data?: Record<string, string> };

export interface SendBatchParams {
  /** Up to 1,000 recipients per call. */
  recipients: BatchRecipient[];
  message: string;
  sender?: string;
  linkTracking?: boolean;
  campaign?: string;
}

export interface SkippedCountry {
  country_code: string;
  recipients: number;
  reason: string | null;
}

export interface SendBatchResponse {
  campaign_id: string;
  recipients_queued: number;
  invalid_numbers?: string[];
  duplicates_removed?: number;
  opted_out_count?: number;
  skipped?: SkippedCountry[];
  credits_used: number;
  credits_remaining?: number;
}

export interface Message {
  id: string;
  recipient: string;
  body: string;
  status: string;
  sent_at: string | null;
}

export interface DeliveryReceipt {
  status: string;
  received_at: string;
}

export interface MessagePayload {
  message: Message;
  delivery_receipt: DeliveryReceipt | null;
}

export interface InboundMessage {
  id: string;
  user_id: string;
  campaign_id: string | null;
  recipient: string;
  sender: string;
  body: string;
  status: string;
  direction: "inbound";
  sent_at: string | null;
  created_at: string;
  in_reply_to: string | null;
  is_optout: boolean;
  reply_to_body: string | null;
}

export interface InboxParams {
  limit?: number;
  offset?: number;
  /** Filter by sender number (partial match). */
  from?: string;
  dateFrom?: string;
  dateTo?: string;
}

export interface InboxResponse {
  messages: InboundMessage[];
  total: number;
  limit: number;
  offset: number;
}

export interface Optout {
  number: string;
  created_at: string;
}

export interface OptoutsResponse {
  optouts: Optout[];
}

export interface Campaign {
  id: string;
  name: string | null;
  message_body: string;
  recipient_count: number;
  parts_per_message: number;
  total_credits: number;
  status: string;
  created_at: string;
  scheduled_at: string | null;
}

export interface CampaignResponse {
  campaign: Campaign;
  stats: { total: number; delivered: number; failed: number };
  messages: Record<string, unknown>[];
  limit: number;
  offset: number;
}

export interface AccountSummary {
  id: string;
  business_name: string | null;
  created_at: string;
  parent_account_id: string | null;
}

export interface AccountDetail extends AccountSummary {
  email: string;
  sending_number: string | null;
  credits: number;
  verified_phone: string | null;
  account_status: string;
  restricted: boolean;
  billing_model: "prepaid" | "postpaid";
  postpaid_price_per_credit: number | null;
  prepaid_price_per_credit: number | null;
  daily_send_limit: number | null;
  default_sender_id_value: string | null;
  hierarchy_enabled: boolean;
  optout_exempt: boolean;
  managed_by_parent: boolean;
  team_access_from_parent: boolean;
  inherit_parent_senders: boolean;
  user_count: number;
  number_count: number;
}

export interface CreateAccountParams {
  businessName: string;
  /** Required unless managedByParent is true. */
  email?: string;
  dailyLimit?: number;
  managedByParent?: boolean;
  teamAccessFromParent?: boolean;
  optoutExempt?: boolean;
  seedCredits?: number;
  /** Only valid within a single ABN. */
  inheritParentSenders?: boolean;
}

export interface CreateAccountResponse {
  account_id: string;
  id: string;
  email: string;
  inherit_parent_senders?: boolean;
  warning?: string;
}

export interface UpdateAccountParams {
  businessName?: string;
  dailyLimit?: number;
  optoutExempt?: boolean;
  teamAccessFromParent?: boolean;
  inheritParentSenders?: boolean;
}

export interface UpdateAccountResponse {
  ok: boolean;
  inherit_parent_senders?: boolean;
  warning?: string;
}

export interface OkResponse {
  ok: boolean;
}

export interface DeleteAccountResponse {
  ok: boolean;
  scheduled_for_deletion: boolean;
}

export interface CreditTransferResponse {
  ok: boolean;
  direction: "allocate" | "recall";
  amount: number;
}

export interface TeamMember {
  id: string;
  owner_id: string;
  member_id: string | null;
  email: string;
  name: string | null;
  can_send: boolean;
  can_billing: boolean;
  status: "pending" | "active";
  invited_at: string | null;
  accepted_at: string | null;
}

export interface AccountUser extends TeamMember {
  auto_via_hierarchy: boolean;
  source: "direct" | "parent";
  managed_here: boolean;
}

export interface InviteUserParams {
  email: string;
  name?: string;
  canSend?: boolean;
  canBilling?: boolean;
}

export interface InviteUserResponse {
  success: boolean;
  email_sent: boolean;
  error_message?: string | null;
  invite_link?: string | null;
}

export interface AccessSettings {
  managed_by_parent: boolean;
  team_access_from_parent: boolean;
  direct_team: TeamMember[];
  eligible_parent_team: TeamMember[];
}

export interface SetAccessParams {
  managedByParent?: boolean;
  teamAccessFromParent?: boolean;
}

export interface ApiKey {
  id: string;
  user_id: string;
  name: string;
  prefix: string;
  created_at: string;
  last_used_at: string | null;
  revoked_at: string | null;
}

export interface CreatedApiKey {
  id: string;
  /** The full API key. Shown once — store it securely. */
  key: string;
  prefix: string;
}

export interface TextoNumber {
  id: string;
  number: string;
  label: string | null;
  provider: string | null;
  assigned_to: string | null;
  assigned_at: string | null;
  created_at: string;
  price_monthly: number | null;
}

export interface AvailableNumber {
  id: string;
  number: string;
  label: string | null;
  provider: string | null;
  price_monthly: number | null;
}

export interface AvailableNumbersResponse {
  numbers: AvailableNumber[];
  limit: number;
  offset: number;
}

export interface PurchaseNumberParams {
  /** A specific available number. When omitted the next available one is used. */
  number?: string;
  label?: string;
  country?: "AU" | "NZ";
}

export interface PurchasedNumber {
  number: string;
  number_id: string;
  label: string | null;
  stripe_subscription_id: string;
  status: "active";
}

export interface WebhookEndpoint {
  user_id: string;
  url: string;
  enabled: boolean;
  signing_enabled: boolean;
  created_at: string;
  updated_at: string;
}

export interface WebhooksResponse {
  delivery_receipt: WebhookEndpoint | null;
  inbound: WebhookEndpoint | null;
}

export interface WebhookUpsertParams {
  /** Must start with https:// */
  url: string;
  enabled?: boolean;
}

export interface ReportSummary {
  messages: {
    total: number;
    parts: number;
    sent: number;
    delivered: number;
    failed: number;
  };
  credits_consumed: number;
  inbound: number;
  optouts: number;
}

export interface ReportParams {
  from?: string;
  to?: string;
  direction?: "all" | "outbound" | "inbound";
  status?: string;
  country?: string;
  campaignId?: string;
  keyword?: string;
  number?: string;
}

export interface AccountReport {
  account_id: string;
  from: string;
  to: string;
  filters: {
    direction: string;
    status: string | null;
    country: string | null;
    campaign_id: string | null;
    keyword: string | null;
    number: string | null;
  };
  summary: ReportSummary;
}

export interface GroupReportRow extends ReportSummary {
  account_id: string;
  business_name: string | null;
  delivery_rate: number;
}

export interface GroupReport {
  from: string;
  to: string;
  accounts: GroupReportRow[];
  grand_total: ReportSummary;
}

/** Body posted to the delivery receipt webhook. */
export type DeliveryReceiptEvent = MessagePayload;

/** Body posted to the inbound message webhook. */
export interface InboundEvent {
  event: "message.inbound";
  message_id: string;
  from: string;
  to: string;
  body: string;
  received_at: string;
  in_reply_to: string | null;
  is_optout: boolean;
}
